/*
 * generated by Xtext 2.16.0
 */
package com.synflow.cx.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.synflow.cx.CxRuntimeModule;
import com.synflow.cx.CxStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CxIdeSetup extends CxStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CxRuntimeModule(), new CxIdeModule()));
	}
	
}
